INSERT INTO price VALUES(10);
INSERT INTO price VALUES(15);
INSERT INTO price VALUES(20);
INSERT INTO price VALUES(25);
INSERT INTO price VALUES(30);
INSERT INTO price VALUES(35);
INSERT INTO price VALUES(40);


